# Generated by Django 5.2.5 on 2025-10-17 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('Manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Manager_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Cost_price', models.IntegerField()),
                ('product_description', models.TextField(null=True)),
                ('Selling_price', models.IntegerField()),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('Quantity', models.IntegerField()),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category')),
                ('Supplier_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='product.supplier')),
                ('Warehouse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='product.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='product.warehousemanager'),
        ),
    ]
