# Generated by Django 5.1.3 on 2025-10-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_itemlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="warehousemanager",
            name="Manager_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
